# Generated by Django 4.1.7 on 2023-04-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("EduTracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="mark",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="EduTracker.student",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marks",
                to="EduTracker.student",
            ),
        ),
    ]
