# Generated by Django 4.1.7 on 2023-04-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("EduTracker", "0002_alter_student_options_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mentor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentee",
                to="EduTracker.teacher",
            ),
        ),
    ]
