# Generated by Django 4.1.7 on 2023-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EduTracker", "0003_alter_student_mentor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mark",
            unique_together={("student", "exam")},
        ),
    ]
