# Generated by Django 4.1.7 on 2023-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EduTracker", "0004_alter_mark_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="mark",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
